---
# tasks file for deploy_computenode
- name: Install Slurm
  yum:
    name: "{{item}}"
    state: present
    disable_gpg_check: yes
  with_items:
    - "/tmp/slurm-{{version}}-1.el8.x86_64.rpm"
    - "/tmp/slurm-slurmd-{{version}}-1.el8.x86_64.rpm"
    - "/tmp/slurm-perlapi-{{version}}-1.el8.x86_64.rpm"