---
# tasks file for munge

- name: Create munge group
  group:
    name: munge
    state: present

- name: Create munge user
  user:
    name: munge
    group: munge
    shell: /usr/sbin/nologin
    system: yes
    state: present

- name: Copy Munge key to all nodes
  copy:
    src: munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400
  notify:
  - munge is restarted

- name: Start and enable Munge service
  systemd:
    name: munge
    state: started
    enabled: yes

- name: Create slurm group
  group:
    name: slurm
    state: present

- name: Create slurm user
  user:
    name: slurm
    group: slurm
    shell: /usr/sbin/nologin
    system: yes
    state: present

- name: slurm_state_dir exists
  file:
    path: "{{ slurm_state_dir }}"
    owner: slurm
    group: slurm
    mode: 0755
    state: directory

- name: Configure Slurm on all node
  template:
    src: slurm.conf
    dest: /etc/slurm/slurm.conf
    owner: slurm
    mode: 0644

- name: All plugins are installed
  yum: name={{item}} state=present
  with_items:
    - slurm-pam_slurm
    - slurm-perlapi
    - libcgroup

- name: Modify GRUB_CMDLINE_LINUX
  template:
    src: grub.j2
    dest: /etc/default/grub
    owner: root
    mode: 0644

- name: Update grub.cfg
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Configure cgroup on all node
  template:
    src: cgroup.conf
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    mode: 0644
